# Generated by Django 2.2.9 on 2020-01-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200113_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_post', 'can post'),)},
        ),
    ]
